<?php	
	$slideshowEnabled = Mage::getStoreConfig('customadmin/slideshow/enabled', Mage::app()->getStore()->getId());
	if ($slideshowEnabled): ?>
	
	<?php $cfg = $this->getSlideshowConfig(); ?>
    <div class="the-slideshow slideshow-wrapper" style="min-height:337px;">    
        <ul class="slideshow">

		<?php foreach ($this->getStaticBlockIds() as $bid): ?>
        	<?php if (!empty($bid)): ?>
        		<?php echo '<li class="slide">' . $this->getLayout()->createBlock('cms/block')->setBlockId($bid)->toHtml() . '</li>'; ?>
			<?php endif; ?>
		<?php endforeach; ?>
        
        <?php foreach ($this->getImgUrls() as $imgUrl): ?>
            <li class="slide">
                <img src="<?php echo $imgUrl; ?>" alt="Slide" />
            </li>
		<?php endforeach; ?>
        
        </ul>
    </div>
<?php /*    <script type="text/javascript">
    //<![CDATA[
	
	jQuery(function() {
		//$.noConflict();
		jQuery(".slideshow").cycle({
			<?php
			//Print slideshow configuration
			foreach ($this->getSlideshowConfig() as $cfg)
				echo "{$cfg['label']}: {$cfg['value']}, ";
			?>
			pager: '#home-slides-pager',
			prev: '#home-slides-prev',
			next: '#home-slides-next'
		});
	});
    //]]>
    </script> */ ?>
<?php endif; ?>

