<div class="padder">
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <div class="page-head">
        <h3><?php echo $this->__('Return Created Successfully') ?></h3>
    </div>
    <div>
		<?php echo $this->__('Your Return has been succesfully submitted. <br/>
        Our customer service department will be contacting you regarding your Return.<br/>
        Any updates on your Return can be viewed by logging into your account and going to "My Returns". <br/>'); ?>
    </div>

</div>