
<?php
$order = Mage::registry( 'rma_order' );
$items = $order->getItemsCollection();
?>

<?php
$thisRMA_customerId = $order->getCustomerId();
$thisRMA_storeId = $order->getStoreId();
$this_customer = Mage::getSingleton('customer/session')->getCustomer()->getId();
$this_store = Mage::app()->getStore()->getStoreId();

if( ($thisRMA_customerId == $this_customer)
 && ($thisRMA_storeId    == $this_store) )
	{
	?>

<script type="text/javascript">

function validate_form(curr_qty, curr_value, curr_item)
	{
	if (curr_value > curr_qty)
		{
		alert ("The quantity you are trying to return is greater than what is shipped.");
		document.getElementsByName('quantity_'+curr_item)[0].value = curr_qty;
		document.getElementById("addtorma_"+curr_item).checked = true;
		}
	if (curr_value == 0 && document.getElementById("addtorma_"+curr_item).checked==true)
		{
		document.getElementById("addtorma_"+curr_item).checked = false;
		}
	if (curr_value>0)
		{
		document.getElementById("addtorma_"+curr_item).checked = true;
		}
	}

function isNumberKey(textboxIn, evt)
{
	   if (!evt)
	   	evt = window.event;
	   var charCode = (evt.which) ? evt.which : evt.keyCode;
		 if (charCode > 31 && (charCode < 48 || charCode > 57) && charCode != 46) {
			return false;
		}
	
		if(charCode == 46 && textboxIn.indexOf(".") != -1) {
			return false;
		}
	  
	return true;
}
function checkboxupdate(checkbox, qty_to_return, curr_item)
	{
	if(checkbox)
		{
		document.getElementsByName('quantity_'+curr_item)[0].value = qty_to_return;
		}
	else
		{
		document.getElementsByName('quantity_'+curr_item)[0].value = "0";
		}
	}
</script>

<div class="padder">
    <div class="page-head">
    	<h3><?php echo $this->__('Return Items'); ?></h3>
	</div>
    <form action="?" method="post">
    <input type="hidden" name="orderID" value="<?php echo($order->getId()); ?>" />
        <?php //echo $this->getBlockHtml('formkey')?>
        <table cellspacing="0" class="data-table" id="my-orders-table">
            <thead>
                    <tr>
                    <th>
                    </th>
                    <th>
                        <?php echo $this->__('Product Details'); ?>
                    </th>
                    <th class="a-center">
                        <?php echo $this->__('Qty'); ?>
                    </th>
                    <th>
                        <?php echo $this->__('Return'); ?>
                    </th>
            	</tr>
    		</thead>
            <tbody>
            <?php
            foreach( $items as $item )
            {
				$product_id = $item->getProductId();
				
				$product = false;
				$product = Mage::getModel( 'catalog/product' )->load( $product_id );
				
				if(true)
					{
					$items = $order->getAllItems();
					foreach ($items as $itemId => $itema)
						{
						if ($itema->getProductId() == $product_id )
							{
							$product = $itema;
							}
						}
					
                ?>
                <tr>
                    <td>
                        <input type="checkbox" name="items[]" id="addtorma_<?=$product_id?>" value="<?php echo $product_id?>" checked="checked" onclick="checkboxupdate(this.checked, <?php echo($item->getQtyShipped() - $item->getQtyRefunded()); ?>, <?php echo $product_id?>);"/>
                    </td>
                    <td>
                        <h6><?php echo htmlentities( $product->getName() )?></h6>
                        <?php echo $this->__('Part no:'); ?> <?php echo htmlentities( $product->getSku() )?><br/>
                        <?php echo $this->__('Serial #:'); ?> <input type="text" name="serial_<?php echo $product_id?>"  value="" class="input_serial" /><br/>
                        <?php echo $this->__('Reason for Return');?><br/> 
                        <textarea name="reason_<?php echo $product_id?>" style="width:465px;" rows="5"></textarea><br/>
                        <?php echo $this->__('Type of Return'); ?> 
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <input type="radio" name="type1_<?php echo $product_id?>" value="Replacement" checked="checked"/> <?php echo $this->__('Replacement'); ?> &nbsp;&nbsp;&nbsp;&nbsp;
                        <input type="radio" name="type1_<?php echo $product_id?>" value="Refund" /> <?php echo $this->__('Refund'); ?>
                    </td>
                    <td class="a-center">
                        <h6><?php echo $item->getQtyShipped() - $item->getQtyRefunded() ?></h6>
                    </td>
                    <td>
                        <input style="width:40px;" type="text" name="quantity_<?php echo $product_id?>"  value="<?php echo $item->getQtyShipped() - $item->getQtyRefunded()?>" class="input_qty" onchange="validate_form(<?php echo $item->getQtyShipped() - $item->getQtyRefunded() ?>, this.value, <?php echo $product_id?>)"/><span class="required">&nbsp;*</span>
                    </td>
                </tr>
                <?php
            }}
            ?>
        </tbody>
</table>
<script type="text/javascript">decorateTable('my-orders-table')</script>


        <div class="button-set">
        <p class="required" style="float: right;"><?php echo $this->__('* Required Fields') ?></p><br />
        <a href="<?php echo $this->getBackUrl() ?>" class="left">&laquo; <?php echo $this->__('Back') ?></a>
        <br/>
        <button type="submit" class="button" title="<?php echo $this->__('Submit RMA') ?>" style="float:right;"><span><span><?php echo $this->__('Submit RMA') ?></span></span></button>
    	</div>
    </form>
</div>
<?php
	}
else
	{
	$notCustomer = false;
	$notStore = false;
	if($thisRMA_customerId != $this_customer) {$notCustomer = true;}
	if($thisRMA_storeId    != $this_store) {$notStore = true;}	
	
	?>
   <div class="padder">
    <div class="page-head button-level">
        <h3>Access Denied.</h3>
        <div style="color: #FFF; padding-left: 20px;">
		  <?php if($notCustomer) { ?><br /><b>You are not the customer associated with this order.</b><? } ?>
        <?php if($notStore) { ?><br /><b>You are not viewing the correct store associated with this order.</b><? } ?>
        </span>
    </div>
    </div>

<?php
	}
?>
