<?php

	$_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    $galleryImages = $_product->getMediaGalleryImages();
    $config = Mage::helper("CustomZoom")->getConfig();
?>
<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
<script type="text/javascript">

$(document).ready(function(){
    $("#wrap").css("z-index","110");    
});
</script>
	<div id="image">
        <?php $firtsImage = Mage::helper("CustomZoom")->imageToVarien($_product); ?>
        <a href='<?php echo $firtsImage->getUrl()?>' class='custom-zoom' id='zoom' rel="<?php echo $config['conf'] ?>">
            <img src="<?php echo Mage::helper("CustomZoom")->resizeImage($_product, $firtsImage, $config['fixSize'], $config['imgSize'])?>" alt='<?php echo $this->htmlEscape($_product->getName()) ?>' style="<?php echo $config['fixSize'].":".$config['imgSize'] ?>px" title="" />
        </a>
    </div>
<?php else: ?>
	<p class="product-image">
		<?php
			$_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(265).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
			echo $_helper->productAttribute($_product, $_img, 'image');
		?>
	</p>
<?php endif; ?>

<?php if (count($galleryImages) > 0): ?>
<div class="more-views" id="zoom-gallery" style="display:<?php echo count($galleryImages)>1?"block":"none"?>">
	<h4><?php echo $this->__('More Views') ?></h4>
    <ul>
    <?php foreach ($galleryImages as $_image): ?>
        <li>
        <?php $_smallImg = Mage::helper("CustomZoom")->resizeImage($_product, $_image, $config['fixSize'], $config['imgSize']); ?>
        <a href="<?php echo $_image->url; ?>" class="custom-zoom-gallery" rel="useZoom: 'zoom', smallImage: '<?php echo $_smallImg ?>'">
        	<img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $_image->getFile())->resize(114); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
		</a>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>

<?php if($_product->getTypeId() == "configurable"): ?>
    <?php $_attrId = Mage::helper("CustomZoom")->getAttributeId() ?>
    <script type="text/javascript">
        jq("document").ready(function(){
            jq("#attribute<? echo $_attrId?>").change(function(){
                var options = spConfig.getAttributeOptions(<? echo $_attrId?>);
                for (x in options) {
                    if (options[x].id == jq(this).val()) {
                        jq.post("<?php echo $this->getUrl("CustomZoom/ajax/images")?>",
                            { products:options[x].products },
                            function(data){
                                fillMediaImages(data);
                            }, "json");
                    }
                }
            });
        });

        function fillMediaImages(data) {
            jq("#zoom").data("zoom").destroy();
            jq("#zoom-gallery ul").empty();
            for (x in data) {
                if (data[x].big) {
                jq("#zoom-gallery ul").append(
                    jq("<li>").append(
                        jq("<a>")
                            .attr("href",data[x].big)
                            .addClass("custom-zoom-gallery")
                            .attr("rel","useZoom: 'zoom', smallImage: '"+data[x].small+"'")
                            .append(
                                jq("<img>").attr("src",data[x].thumb)
                                        .attr("alt",data[x].title)
                                        .attr("title",data[x].title)
                            )
                        )
                    )
                }
            }
            jq("#zoom, .custom-zoom-gallery").CustomZoom();
            jq("#wrap").css("z-index","110");
        }
    </script>
<?php endif; ?>    