

<div id="home-featured">
	<div class="page-title featured-title">
        <h3><?php echo $this->__('Featured products') ?></h3>
    </div>

	<?php
		$_helper = $this->helper('catalog/output');
		$storeId = Mage::app()->getStore()->getId();
		$catalog = $this->getLayout()->createBlock('catalog/product_list')->setStoreId($storeId);

		$collection = Mage::getModel('catalog/product')->getCollection();
		$collection->addAttributeToSelect('featured_product');
		$collection->addFieldToFilter(array(
			array('attribute' => 'featured_product', 'eq' => true),
		));

		if (!$collection->count()) :
	?>
		<p class="note-msg"><?php echo $this->__('There are no featured products at the moment.') ?></p>
	<?php else : ?>
	<div class="category-products-feature">
	<ul class="products-grid">
	<?php
		$i=0;
		foreach ($collection as $_product) :
			$_product = Mage::getModel('catalog/product')->setStoreId($storeId)->load($_product->getId());
		?>
		
	        <?php /*?><li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>"><?php */?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?><?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
	            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
	            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <?php
                $price = $_product->getPrice();
                $specialprice = $_product->getFinalPrice();
				
				?>
                <?php /*?><span class="old_price"><?php echo "$ ". round($price,2); ?></span>			//change by raghu
                <span class="specialprice"><?php echo "$ ". round($specialprice,2); ?></span><?php */?>

				<span class="old_price"><?php echo "$ ". number_format($price,2); ?></span>			
                <span class="specialprice"><?php echo "$ ". number_format($specialprice,2); ?></span>
                
                  <a class="quickview" rel="nofollow" href="<?php echo Mage::getBaseUrl(), 'catalog/ajax_product/view/id/', $_product->getId() ?>"><?php echo $this->__('Quickview') ?></a>	            <?php echo $this->getPriceHtml($_product, true) ?>
	            
	        </li>
	    
        <?php if($i==1)
		       break;
			  else
		       $i++; 
			endforeach ?>
        </ul>
	</div>
	<?php endif ?>
</div>