<div class="imgList">

 <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/queckview/js/queckbox.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('featured_slider/jquery.jcarousel.min.js')?>"></script> 
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('home-slider/skin.css')?>">
<script type="text/javascript">

function mycarousel_initCallback(carousel)
{
    // Disable autoscrolling if the user clicks the prev or next button.
    carousel.buttonNext.bind('click', function() {
        carousel.startAuto(0);
    });

    carousel.buttonPrev.bind('click', function() {
        carousel.startAuto(0);
    });

    // Pause autoscrolling if the user moves with the cursor over the clip.
    carousel.clip.hover(function() {
        carousel.stopAuto();
    }, function() {
        carousel.startAuto();
    });
};

jQuery(document).ready(function() {
   //jQuery.noConflict();
    jQuery('#mycarousel').jcarousel({
        auto: 2,
        wrap: 'last',
        initCallback: mycarousel_initCallback
    });
});

</script> 


<script type="text/javascript" src="<?php echo $this->getSkinUrl('additional_slider/jquery-1.js')?>"></script>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('additional_slider/jquery.js')?>"></script>

<script type="text/javascript">
	jQuery(document).ready(function() {
    	jQuery('#mycarousel111').jcarousel();
});
</script>

<div class=" jcarousel-skin-tango">
<div style="position: relative; display: block;" class="jcarousel-container jcarousel-container-horizontal">
<div style="position: relative;" class="jcarousel-clip jcarousel-clip-horizontal">
<ul style="overflow: hidden; position: relative; top: 0px; margin: 0px; padding: 0px; left: 0px; width: 1060px;" id="mycarousel" class="img-list jcarousel-list jcarousel-list-horizontal">
<?php 
		$_helper = Mage::helper('catalog/category'); 
	    $_categories = $_helper->getStoreCategories(); 
		$media_url=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
		$currentCategory = Mage::registry('current_category'); 
 		if (count($_categories) > 0): 
		foreach($_categories as $_category): ?>
<?php    
				$category_id = $_category->getId(); 
			 	$cur_category = Mage::getModel('catalog/category')->load($_category->getId());
					?>
<?php /*?><img src="<?php echo $media_url.'catalog/category/'.$cur_category['thumbnail'] ?>" />	       
	            <h3> <a href="<?php echo $_helper->getCategoryUrl($_category) ?>"> <?php echo $_category->getName() ?> </a></h3><?php */?>
<?php
				$_category = Mage::getModel('catalog/category')->load($category_id) ;
				$_subcategories = $_category->getChildrenCategories();
				foreach($_subcategories as $_subcategory)
				{
					$sub_category = Mage::getModel('catalog/category')->load($_subcategory->getId());
					?>
<li jcarouselindex="1" style="float: left; list-style: none outside none;" class="jcarousel-item jcarousel-item-horizontal jcarousel-item-1 jcarousel-item-1-horizontal">
  <div class="pro"><a href="<?php echo $_helper->getCategoryUrl($_subcategory) ?>" ><img src="<?php echo $media_url.'catalog/category/'.$sub_category['thumbnail'] ?>" alt="<?php echo $_subcategory->getName() ?>" height="150px" width="150px" /></a> <a class="cat_name_home" href="<?php echo $_helper->getCategoryUrl($_subcategory) ?>" > <?php echo $_subcategory->getName() ?> </a>
    <p><a class="cat_queckview" href="<?php echo $_helper->getCategoryUrl($_subcategory) ?>" ><span>Quick View</span></a></p>
  </div>
</li>
<?php
                           }
			
				 endforeach;
				 echo "</ul>";	
			echo "</div>";	
			endif; ?>
<div disabled="disabled" style="display: block;" class="jcarousel-prev jcarousel-prev-horizontal jcarousel-prev-disabled jcarousel-prev-disabled-horizontal"></div>
<div style="display: block;" class="jcarousel-next jcarousel-next-horizontal"></div>
</div>
</div>
</div>
</div><?php /*?><div class="new-product"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('new_product')->toHtml() ?></div><?php */?>

<div class="new-product"><?php require('new_product.phtml');  ?></div>

<div class="new-product"><?php require('inchoo_bestselling_product.phtml');  ?></div>

<div class="home-banner">
<div class="prodts">
<?php  //require('featured_product.phtml');  ?><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_banner')->toHtml() ?>
  <div class="cls"></div>
</div>
<?php /*?><div class="homCnt"> <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('over_wonova')->toHtml() ?> </div><?php */?>
<div class="homCnt"> <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('about_alamoana')->toHtml() ?> </div>
<div class="cls"></div>
</div>

<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>



<script type="text/javascript">
					//jQuery.noConflict();
                    jQuery(document).ready(function() {
                        jQuery('#logo_slider').jcarousel();
                    });
                    </script>
<div class="logoIcns">
  <ul id="logo_slider" class="jcarousel-clip jcarousel-clip-horizontal">
	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_page_brand')->toHtml() ?>
  </ul>
</div>
<div disabled="disabled" style="display: block;" class="jcarousel-prev jcarousel-prev-horizontal jcarousel-prev-disabled jcarousel-prev-disabled-horizontal"></div>
<div style="display: block;" class="jcarousel-next jcarousel-next-horizontal"></div>
<div class="cls"></div>
</div>
</div>
